// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTableProject.Data;

#nullable disable

namespace TimeTableProject.Data.TimetableMigrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231219060229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TimeTableProject.Entities.TimeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttendanceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Batch")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassRoom")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeTable");
                });
#pragma warning restore 612, 618
        }
    }
}
